{
    "apps": [
        {
            "build_date": "2020-06-10_09:49:09", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "e147c0ae9d3ecd0d2ac4182fb03595b4", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "0.9"
        }, 
        {
            "build_date": "2019-11-01_15:24:52", 
            "changelog": "", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "a372b0e0f1564e594416e4fa38abae3d", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "1.5"
        }, 
        {
            "build_date": "2019-07-10_22:31:48", 
            "changelog": "", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "eb96b6893a78b3dcbff12477c7d2d926", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "1.5"
        }, 
        {
            "build_date": "2019-07-10_22:55:24", 
            "changelog": "", 
            "description": "VPN全家桶, ver 4.29 build 9680", 
            "home_url": "Module_softether.asp", 
            "md5": "00e58bfa9a58cc482fa18a99b56ebe99", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "1.9"
        }, 
        {
            "build_date": "2019-07-09_12:07:54", 
            "changelog": "", 
            "description": "CloudFlare DDNS", 
            "home_url": "Module_cfddns.asp", 
            "md5": "60825d873eb1276029a5c38e83092e31", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "CloudFlare DDNS", 
            "version": "1.0"
        }, 
        {
            "build_date": "2020-03-05_13:42:47", 
            "changelog": "", 
            "description": "易有云 （EasyExplorer） 跨平台文件同步，支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "f0d2298ef75b2ab6102d6927a24973e0", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云", 
            "version": "2.4"
        }, 
        {
            "build_date": "2019-07-09_15:25:58", 
            "changelog": "", 
            "description": "支持多种协议的内网穿透软件", 
            "home_url": "Module_frpc.asp", 
            "md5": "31a6b91802950ad9cbb8d74e86a61e7e", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc内网穿透", 
            "version": "1.6"
        }, 
        {
            "build_date": "2020-07-03_10:41:34", 
            "changelog": "", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "8ec889744cdb3668a29738e650cc99f2", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "1.4.16"
        }, 
        {
            "build_date": "2020-06-10_09:48:46", 
            "changelog": "", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_routerhook.asp", 
            "md5": "cb73cb2fda5e2d627f1cd10a86302d13", 
            "name": "routerhook", 
            "tar_url": "routerhook/routerhook.tar.gz", 
            "title": "RouterHook事件回调", 
            "version": "1.1"
        }, 
        {
            "build_date": "2020-07-03_10:34:36", 
            "changelog": "", 
            "description": "通过pushplus将路由器状态推送到微信上", 
            "home_url": "Module_pushplus.asp", 
            "md5": "36d26cf745fded42527b6667640e3cc4", 
            "name": "pushplus", 
            "tar_url": "pushplus/pushplus.tar.gz", 
            "title": "pushplus全能推送", 
            "version": "0.3"
        }, 
        {
            "build_date": "2019-07-10_20:30:07", 
            "changelog": "", 
            "description": "自动签到", 
            "home_url": "Module_qiandao.asp", 
            "md5": "960b535fc453d4a50603ab4703a523e8", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "自动签到", 
            "version": "1.5"
        }, 
        {
            "build_date": "2019-07-09_14:27:39", 
            "changelog": "", 
            "description": "迅雷快鸟，上网必备神器", 
            "home_url": "Module_fastd1ck.asp", 
            "md5": "2e215561ff817f7d71b017178d846daf", 
            "name": "fastd1ck", 
            "tar_url": "fastd1ck/fastd1ck.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "1.6"
        }, 
        {
            "build_date": "2019-07-09_15:30:13", 
            "changelog": "", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "15716ea90cc0f704749ecdfd69fabb65", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.3"
        }, 
        {
            "build_date": "2020-04-03_15:55:50", 
            "changelog": "", 
            "description": "轻松用U盘挂载jffs", 
            "home_url": "Module_usb2jffs.asp", 
            "md5": "aefc48dc3862559f74eec5573ddf8016", 
            "name": "usb2jffs", 
            "tar_url": "usb2jffs/usb2jffs.tar.gz", 
            "title": "USB2JFFS", 
            "version": "1.6"
        }, 
        {
            "build_date": "2020-06-27_08:48:01", 
            "changelog": "", 
            "description": "一些小功能的插件", 
            "home_url": "Module_rog.asp", 
            "md5": "57d7656d6aac488dfeb138781baf623d", 
            "name": "rog", 
            "tar_url": "rog/rog.tar.gz", 
            "title": "ASUS工具箱", 
            "version": "2.7"
        }, 
        {
            "build_date": "2019-07-09_11:49:54", 
            "changelog": "", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "e827af482d4456441c31faa2866c145b", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "aria2", 
            "version": "2.2"
        }, 
        {
            "build_date": "2020-05-28_15:18:49", 
            "changelog": "", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "88a91c4f1203baf0e97d428eb03ddce4", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.1"
        }, 
        {
            "build_date": "2021-02-01_23:28:23", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "2be38a8a9bd4faf3a0c79a3d1ed54932", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.2"
        }, 
        {
            "build_date": "2021-01-21_23:37:16", 
            "changelog": "", 
            "description": "ddnsto内网穿透", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "83269beb2a78cd328500566310e674fb", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "ddnsto", 
            "version": "2.2"
        }, 
        {
            "build_date": "2020-03-21_20:36:51", 
            "changelog": "", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "8906df146731ebe0b036cf475622f658", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.6"
        }, 
        {
            "build_date": "2020-07-03_10:34:18", 
            "changelog": "", 
            "description": "ddnspod", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "3f2a14e63fcb25105250767e8ec16aef", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "ddnspod", 
            "version": "1.5"
        }, 
        {
            "build_date": "2019-07-19_08:37:35", 
            "changelog": "", 
            "description": "让路由器运行更稳定~", 
            "home_url": "Module_swap.asp", 
            "md5": "f6011cf822f491e3f569789c169ae8ea", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.1"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "690fea89300704b36f71758a354ce670", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.0.9"
}